### ISSUE TITLE
Question: what if one is running a different antivirus?

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [LesFerch/ClearDefenderHistory#2]
Hello. I'd like to use the program to clear out any Defender-cruft. However, I read that the script restarts Defender - and I use a second-party anti-virus and have Defender disabled (or as disabled as it can be without extreme measures).

I could be brave and just try the script. Yet, even if so doing would cause no problems on my system, you might want to put something in the README about this situation.

Thanks for your time.

**Comment by LesFerch** [comment]
I would expect that if a different AV is installed, the script will not cause Defender to start. Note that the stop/start is done by     `Set-MpPreference -DisableRealtimeMonitoring 1/0` as opposed to starting an exe. When I get a chance, I'll test it to be sure.

**Comment by LinuxOnTheDesktop** [comment]
Thanks. I had not actually looked at the script. Just now I did. I know little of Windows's guts so the script did not mean that much to me, but I decided to run it anyway. I did so via a Powershell prompt. The script completed, without giving a visible error, and my third-party antivirus remains functional.
