### ISSUE TITLE
Feature request: Silent launch for ClearDefenderHistory

### ISSUE THREAD

**Issue by Lisa24Jackson** [LesFerch/ClearDefenderHistory#5]
First of all, I'd like to thank you for this wonderful tool. I've encountered a situation where I'd like to add ClearDefenderHistory to the startup so that it clears the history every time after shutting down the computer. However, it's currently quite cumbersome, as there is no silent launch for the tool without command line and dialogs. Could you implement this?

**Comment by LesFerch** [comment]
Done. Use `ClearDefenderHistoryEveryRestart.cmd`. See the readme for details.

**Comment by Lisa24Jackson** [comment]
> Done. Use `ClearDefenderHistoryEveryRestart.cmd`. See the readme for details.

Everything is great, everything works. However, there is one unpleasant nuance compared to the original tool. The task is created in the Task Scheduler even when the history is empty. That's, every time the computer is loaded or restarted, a task is unnecessarily created in the Task Scheduler. This isn't ideal. It would be great if you could also add a check, as was implemented before. That's, if the history is empty (i.e., the "Detections.log" file is missing), then no task is created. Otherwise, a task is created for clearing the history. So the only difference from the original tool would be that no dialog strings would be displayed, making it possible to include it in the autostart.

**Comment by LesFerch** [comment]
You've misunderstood how it's supposed to be used. You're supposed to run `ClearDefenderHistoryEveryRestart.cmd` (as Administrator) just _once_ to create the task and that's it.

The script simply creates a task that you leave in place forever. The task runs as System every time the computer starts (so there's no console flash) which will delete the folder if it exists. It does not need to check for existence. It just has to execute the rd command. If there's no folder to delete, then the rd command silently fails. It's the most efficient way to do it.

There would be nothing gained by running a script that checks for the folder's existence and then creates the task. Such a script would have to be set as a task to run every startup and then it would be the following restart when the history gets cleared.

**Comment by LesFerch** [comment]
In Task Scheduler, you should see a task named `DWDH` (Delete Windows Defender History). You can just delete that task. Also, if you run the original `ClearDefenderHistory.cmd` script, it will overwrite the `DWDH` task with one that removes itself after next restart.

I'm sure Microsoft would not recommend deleting the history automatically on every restart since you may want to check what has been detected, in case there is some potentially malware-related issue. The machine might get restarted before you have a chance to check the history. Personally, I would keep the clearing of the history to a manual procedure.

**Comment by Lisa24Jackson** [comment]
> In Task Scheduler, you should see a task named `DWDH` (Delete Windows Defender History). You can just delete that task. Also, if you run the original `ClearDefenderHistory.cmd` script, it will overwrite the `DWDH` task with one that removes itself after next restart.
> 
> I'm sure Microsoft would not recommend deleting the history automatically on every restart since you may want to check what has been detected, in case there is some potentially malware-related issue. The machine might get restarted before you have a chance to check the history. Personally, I would keep the clearing of the history to a manual procedure.

Okay, thank you very much for the explanation.
